"""
ISF Solution Data Generator
Generated by isf-data-generation skill.

Usage:
    python generate_all.py

Output:
    src/data_engine/output/{entity}.parquet
    src/data_engine/output/manifest.json
"""

import random
import json
import os
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np
import pandas as pd
from faker import Faker

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
fake = Faker()
Faker.seed(SEED)

OUTPUT_DIR = Path("src/data_engine/output")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def weighted_choice(choices: list, weights: list) -> str:
    return random.choices(choices, weights=weights, k=1)[0]


def lognormal_value(mean: float, sigma: float,
                    min_val: float = None, max_val: float = None) -> float:
    val = np.random.lognormal(np.log(mean), sigma)
    if min_val is not None:
        val = max(val, min_val)
    if max_val is not None:
        val = min(val, max_val)
    return round(val, 2)


def random_date(start_year: int = 2023, end_year: int = 2025) -> str:
    start = datetime(start_year, 1, 1)
    end = datetime(end_year, 12, 31)
    delta = (end - start).days
    return (start + timedelta(days=random.randint(0, delta))).isoformat()


# --- Entity generators below (customize per solution) ---

# def generate_customers(n: int) -> pd.DataFrame: ...
# def generate_transactions(n: int, customer_ids: list) -> pd.DataFrame: ...


def save_entity(df: pd.DataFrame, name: str) -> dict:
    path = OUTPUT_DIR / f"{name}.parquet"
    df.to_parquet(path, index=False, engine="pyarrow", compression="snappy")
    return {"entity": name, "rows": len(df), "file": str(path)}


def main():
    manifest = {
        "seed": SEED,
        "generated_at": datetime.utcnow().isoformat(),
        "entities": []
    }

    # --- Generate in dependency order ---
    # Example:
    # customers = generate_customers(10000)
    # manifest["entities"].append(save_entity(customers, "customers"))
    #
    # transactions = generate_transactions(50000, customers["CUSTOMER_ID"].tolist())
    # manifest["entities"].append(save_entity(transactions, "transactions"))

    manifest_path = OUTPUT_DIR / "manifest.json"
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)

    print(f"[OK] Generation complete. {len(manifest['entities'])} entities.")
    print(f"[OK] Manifest: {manifest_path}")


if __name__ == "__main__":
    main()
